name: checks
on: [push]
jobs:
  validate-node-config-schema:
    name: validate json schema for node configs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cardinalby/schema-validator-action@v3
        with:
          file: 'meta/nodes.schema.json'
  validate-generated-schema:
    name: validate generated schema.json
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cardinalby/schema-validator-action@v3
        with:
          file: 'schema.json'
  validate-node-configs:
    name: validate node configs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cardinalby/schema-validator-action@v3
        with:
          schema: 'meta/nodes.schema.json'
          file: 'meta/nodes/*.json'
